blackboard/urls.py
from django.urls import path

from . import views

app_name = 'blackboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new_session, name='new_session'),
    path('save', views.save_session, name='save_session'),
    path('delete', views.delete_session, name='delete_session'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('week/<int:year>/<int:week_id>/', views.week_overview, name='week_overview'),
    path('set/<int:year>/<int:week_id>/', views.week_poll, name='week_poll'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blackboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class RunningSession(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    location = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return "%s" % (self.title)

blackboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import RunningSession
from django.contrib.auth.decorators import login_required

'''
Index View of the blackboard.
'''


def index(request):
    sessions = RunningSession.objects.all()
    context = {'sessions': sessions, 'bb_active': True}
    return render(request, 'blackboard/index.html', context)


'''
View to define new RunningSessions
'''


@login_required
def new_session(request):
    context = {}
    return render(request, 'blackboard/new_session_form.html', context)


'''
View to create a new RunningSessions
Required POST parameters are:
- title
- description
- location
'''


@login_required
def save_session(request):
    title = request.POST.get("title", "")
    description = request.POST.get("description", "")
    location = request.POST.get("location", "")
    current_user = request.user

    if title is not "" and description is not "" and location is not "":
        session = RunningSession(
            title=title, description=description, location=location, author=current_user)
        session.save()
        return redirect('blackboard:index')
    else:
        context = {'title': title,
                   'description': description, 'location': location}
        return render(request, 'blackboard/new_session_form.html', context)


'''
View to confirm and delete RunningSessions
'''


@login_required
def delete_session(request):
    id = request.GET.get('id', None)
    confirmation = request.GET.get('confirmation', None)
    session = None
    if id == None:
        # no id... user should not be here!
        # redirect to blackboard
        return redirect('blackboard:index')
    else:
        session = RunningSession.objects.filter(id=id)
        if len(session) == 0:
            # given id does not exist
            # redirect to blackboard
            return redirect('blackboard:index')
        else:
            session = session[0]    # thats ugly!
    if not request.user.is_authenticated:
        # user is not authentificated and should not be here!
        # should not be possible because of @login_required
        # redirect to blackboard!
        return redirect('blackboard:index')
    elif request.user == session.author:
        # current user is owner of this session
        if confirmation is not None and confirmation == "True":
            # delete and redirect to blackboard
            session.delete()
            return redirect('blackboard:index')
        else:
            # user is allowed to delete this session but should confirm the action
            context = {'session': session}
            return render(request, 'blackboard/delete_confirmation.html', context)
    else:
        # user is authentificated but not the author of the session.
        # redirect
        return redirect('blackboard:index')

    # in case we reached this line of code none of the previous condition applied.
    # thats a problem!
    # to prevent damage, redirect to blackboard.
    return redirect('blackboard:index')

blackboard/templates/blackboard/blackboard_entry.html
<div class="card" style="width: 18rem;">
  <div class="card-header">
    <h5 class="card-title">{{ session.title }}</h5>
  </div>
    <div class="card-body">
      <p class="card-text">{{ session.description }}</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Treffpunkt:<br>{{ session.location }}</small>
    </div>
    <div class="card-footer">
      <small class="text-muted">Autor:<br>Mark</small>
    </div>
    {% if session.author.username == user.get_username %}
      {% if 'id' not in request.GET %}
      <div class="card-footer">
        <small class="text-muted"><a href="{% url 'blackboard:delete_session' %}?id={{ session.id }}">Löschen</a></small>
      </div>
      {% endif%}
    {% endif %}
</div>

blackboard/templates/blackboard/delete_confirmation.html
{% extends 'lauftreff/base_layout.html' %}

{% block content %}
<div class="mb-5">
Sind sie sicher, dass dieser Aushang vom schwarzen Brett entfernt werden soll?
</div>
<div class="mb-5">
{% include "blackboard/blackboard_entry.html" %}
</div>
<div class="mb-5">
<form method="get">
  <a href="{% url 'blackboard:delete_session' %}?id={{ session.id }}&confirmation=True" class="btn btn-light">Ja</a>
  <a href="{% url 'blackboard:index' %}" class="btn btn-light">Nein</a>
</form>
</div>
{% endblock %}

{% block well %}
  <h2>Schwarzes Brett</h2>
{% endblock %}

blackboard/templates/blackboard/index.html
{% extends 'lauftreff/base_layout.html' %}

{% block content %}
<div class="mb-5">
Hier findet sich ein schwarzes Brett auf dem Nutzer ihre geplanten Lauftermine veröffentlichen können.<br>
Dazu wird der Button "Neuen Lauf veröffentlichen" gewählt und der Lauf im darauf folgenden Dialog definiert.<br>
Interessierte Nutzer können sich anschließend diesem Lauf anschließen.<br>
Das schwarze Brett ist öffentlich zugänglich. Um geplante Läufe zu veröffentlichen und zu verwalten, wird jedoch ein Account benötigt.
{% if not user.is_authenticated %}Neue Accounts können <a href="{% url 'signup' %}">hier</a> angelegt werden.{% endif %}
</div>

<div class="container">
  <div class="row">
      {% for session in sessions %}
      <div class="col-6 mb-5">{% include "blackboard/blackboard_entry.html" %}</div>

          <!-- if last column in row -->
          {% if forloop.counter|divisibleby:"2" and not forloop.last %}
          </div><div class="row">
          {% endif %}

      {% endfor %}
  </div>
</div>
{% endblock %}

{% block submenu %}
  <a class="btn btn-light" href="{% url 'blackboard:new_session' %}">Neuen Lauf veröffentlichen</a>
{% endblock %}

{% block well %}
  <h2>Schwarzes Brett</h2>
{% endblock %}

blackboard/templates/blackboard/new_session_form.html
{% extends 'lauftreff/base_layout.html' %}

{% block content %}
<form method="post" action="{% url 'blackboard:save_session' %}">
  {% csrf_token %}
  <div class="form-group">
    <label>Überschrift</label><br>
    <input type="text" name="title">
  </div>
  <div class="form-group">
    <label>Beschreibung</label><br>
    <textarea  cols="50" rows="10" name="description"></textarea>
  </div>
  <div class="form-group">
    <label>Treffunkt</label><br>
    <input type="text" name="location">
  </div>
  <button type="submit" class="btn btn-light">Veröffentlichen</button>
</form>
{% endblock %}

{% block well %}
  <h2>Schwarzes Brett</h2>
{% endblock %}