blackboard/urls.py
from django.urls import path

from . import views

app_name = 'blackboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new_session, name='new_session'),
    path('save', views.save_session, name='save_session'),
    path('delete', views.delete_session, name='delete_session'),
]

lauftreff/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls import url

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^accounts/signup/$', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
    path('blackboard/', include('blackboard.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('week/<int:year>/<int:week_id>/', views.week_overview, name='week_overview'),
    path('set/<int:year>/<int:week_id>/', views.week_poll, name='week_poll'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

lauftreff/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class PasswordField(forms.CharField):
    widget = forms.PasswordInput

class SignUpForm(UserCreationForm):
    username = forms.CharField(label="Benutzername", max_length=30, required=True, help_text='')
    email = forms.EmailField(label="E-Mail Adresse (optional)", max_length=254, required=False, help_text='Aktuell wird die E-Mail Adresse nicht genutzt. Möglicherweise wird diese Adresse in Zukunft irgendwann für einen Newsletter oder eine tägliche / wöchentliche Zusammenfassung genutzt.')
    password1 = PasswordField(label="Passwort", max_length=150, required=True, help_text='')
    password2 = PasswordField(label="Passwort wiederholen", max_length=150, required=True, help_text='')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email' )

lauftreff/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import SignUpForm

def index(request):
    context = {'headline': "Planung"}
    return render(request, 'lauftreff/index.html', context)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

lauftreff/templates/lauftreff/base_layout.html
{% load static %}

<html>
  <head>
    <title>Lauftreff Tool</title>
    <link rel="stylesheet" href="{% static "lauftreff/css/bootstrap.min.css" %}">
    {% block css %}
    {% endblock %}
    <style>
    .well {

        background: #2c3e50;
        text-align: center;
        padding: 10px 0 0px 0;
        color: #fff;

    }
    </style>
  </head>
  <body>
    {% include "lauftreff/main_menu.html" %}
    <div class="well">
      <div class="container mt-2 pb-2 mb-2">
      {% block well %}
      {% endblock %}
      </div>
    </div>

    <div class="container">
      <div class="col-12 py-md-3 pl-md-5 bd-content">
        <div class="row">
          <div class="col-9">
          {% block content %}
          {% endblock %}
          </div>
          <div class="col-3">
            <div class="container">
              {% block submenu %}
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static "lauftreff/js/bootstrap.min.js" %}"></script>
    <script src="{% static "lauftreff/js/jquery.min.js" %}"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

lauftreff/templates/lauftreff/index.html
{% extends 'lauftreff/base_layout.html' %}

{% block content %}
<div class="container mb-5">
  <h3>Text</h3>
</div>

<div class="container mb-5">
  <h3>Text</h3>
</div>

<div class="container mb-5">
  <h3>Text</h3>
</div>
{% endblock %}

{% block well %}
  <h2>Dashboard</h2>
{% endblock %}

lauftreff/templates/lauftreff/main_menu.html
<div class="navbar navbar-expand-lg bg-light navbar-light">
  <div class="container">
  <div class = "page-header">
    <a class="navbar-brand" href="{% url 'index' %}">
     <h4>
        Lauftreff
        <span style="color:silver; font-weight:700"><small>BETA</small></span>
       </h4>
    </a>
  </div>
  <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item{% if bb_active %} active{% endif %}"><a class="nav-link" href="{% url 'blackboard:index' %}">Schwarzes Brett</a></li>
                    <li class="nav-item{% if tm_active %} active{% endif %}"><a class="nav-link" href="{% url 'polls:index' %}">Terminfindung</a></li>
                </ul>
                <ul  class="nav navbar-right navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="navbar-text">{{ user.get_username }}&nbsp;</li>
                    <li class="nav-item"><a href="{% url 'logout' %}"  class="nav-link">Logout</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="{% url 'signup' %}" class="nav-link">Registrieren</a></li>
                    {% endif %}
                </ul>
            </div>
          </div>
</div>
<div class="navbar-pad"></div>